### PR TITLE
Etna gem bug descriptions

### PR DESCRIPTION
**Pull request by coleshaw**
This PR fixes my changes to the gem in #315, specifically regarding attribute descriptions. The previous PR was flagging all descriptions as "new" because of the discrepency between `description` and `desc` in the different systems we're using. This PR patches that and forces the comparison to look at `desc` only, to detect if the attribute has been edited.

### CODE REVIEW

**Comment by graft** [comment]
Can we do it the other way? I have wanted to deprecate "desc" for years.

**Comment by coleshaw** [comment]
Just get rid of `desc` and consolidate on `description`? Let me look into how far that's propagated.

**Comment by corps** [comment]
@coleshaw Let me know if you need help recording a new VCR tape for those failing tests.

**Comment by coleshaw** [comment]
Thanks @corps , I'll let you know. A bit slower because of half-days this week, but I'll try re-recording later this morning.

**Pull request merged**
