### PR TITLE
Metis#find provides down load urls in response

### PR DESCRIPTION
**Pull request by corps**
Some adjustments so that the find endpoint can still efficiently return download_urls

### CODE REVIEW

**Comment by graft** [comment]
Nitty pick, indirectly related to this change - it makes me itchy to have methods relating to a single controller collecting on Metis::Controller, which in my mind should only contain a very few pan-controller methods - could we move them inside Metis::Query?

**Comment by corps** [comment]
> Nitty pick, indirectly related to this change - it makes me itchy to have methods relating to a single controller collecting on Metis::Controller, which in my mind should only contain a very few pan-controller methods - could we move them inside Metis::Query?

Hmm.  I don't disagree, but it can't go specifically in Metis::Query because it needs a reference to the request due to the way the hmac url generation works.

**Comment by graft** [comment]
> Hmm. I don't disagree, but it can't go specifically in Metis::Query because it needs a reference to the request due to the way the hmac url generation works.

Argh, what a deep rabbit hole that turns out to be, ending in Etna::Server.route_path, where the best part of the joke is:
```
      def route_path(request,name,params={})                                                        
        route = routes.find do |route|                                                              
          route.name.to_s == name.to_s                                                              
        end                                                                                         
        return route ? route.path(params) : nil                                                     
      end 
```

It doesn't even use the request! The only place it gets used is download_url uses request.host, which should probably be hard-coded anyway rather than taken from the request, which seems somewhat dodgy.

**Comment by corps** [comment]
I tried pulling the logic out of the metis controller, but ended up having failing tests because both folder controller and bucket controller depend on the logic.  At best I can extract it to a module and include that in both classes.  Thoughts?

**Comment by graft** [comment]
These days i tend to prefer the service object to the injected module and the method-from-nowhere. Looks like all of these are just extending the interface of FolderPathCalculator and could be folded into that, which might be instantiated directly in the controller.

My other habit in this situation, maybe only mildly better, is putting e.g. folder-relates helpers as class methods on Metis::Folder.

**Pull request merged**
