### PR TITLE
some styling updates

### PR DESCRIPTION
**Pull request by graft**
Just a few style tweaks, nothing final yet. Mostly left the session manager alone.

### CODE REVIEW

**Comment by coleshaw** [comment]
Thanks! I think I had done some similar changes this morning.

Also, some of the nav / link changes will require corresponding deployment config changes?

**Comment by graft** [comment]
Hmm yeah maybe I shouldn't have hooked up all the nav components yet until we are ready to deploy vulcan...

**Review by coleshaw — APPROVED** [review]
Looks good, if you can clean up the conflicts (apologies). I'm going to stop doing styling stuff for a bit, so there shouldn't be any more conflicts. I'm going to work on connecting outputs and steps instead.

**Comment by coleshaw** [comment]
Okay @graft , I've cleaned up the conflicts with what I did this morning. Once it's merged I'll take another look in the browser and make sure the merge was clean...

**Pull request merged**
