### PR TITLE
Gvaihir/geoline debug

### PR DESCRIPTION
**Pull request by Gvaihir**
Debugged mapping of one-to-many data queries

### CODE REVIEW

**Review by coleshaw — APPROVED** [review]

**Comment by Gvaihir** [comment]
I've renamed some stuff

**Comment by dtm2451** [comment]
For the characteristics step:
```
The answer yes is not in allowed answers
Provide an allowed answery
1:	tissue
2:	cell type
3:	treatment
4:	genotype
5:	disease state
```
answer**y**, typo?  But also is it possible to request to add multiple?  I've tried a few ways to say "1,2,3" but none have worked.

**Comment by Gvaihir** [comment]
> For the characteristics step:
> 
> ```
> The answer yes is not in allowed answers
> Provide an allowed answery
> 1:	tissue
> 2:	cell type
> 3:	treatment
> 4:	genotype
> 5:	disease state
> ```
> 
> answer**y**, typo? But also is it possible to request to add multiple? I've tried a few ways to say "1,2,3" but none have worked.

It's a typo. Allows single integer as an input. If you have multiple - you will have to do it in additional steps

**Comment by dtm2451** [comment]
Trying again, now giving `raw_counts_h5` as the processed counts file, it looks like there is a malformed query somewhere.  But I'm not sure where.  Perhaps you could add a hint at the current data grab goal in the error messaging?

<details>
  <summary>Click to expand choices and traceback</summary>

```
Is sc_seq:tube_name correct for title?
ANSWER OPTIONS:
y:	yes
Or type the correct attribute name:	  
0:	back
STOP:	cancel pipeliney

Is sc_seq:biospecimen correct for source name?
ANSWER OPTIONS:
y:	yes
Or type the correct attribute name:	  
0:	back
STOP:	cancel pipelinesc_seq:biospecimen_group

Is subject:name correct for organism?
ANSWER OPTIONS:
y:	yes
Or type the correct attribute name:	  
0:	back
STOP:	cancel pipelinesubject:species

Do you want to add a sample characteristic?
ANSWER OPTIONS:
y:	yes
n:	no - same as STOP
0:	back
STOP:	cancel pipeliney
1:	tissue
2:	cell type
3:	treatment
4:	genotype
5:	disease state2
Enter attribute name for this characteristicsc_seq:cell_fraction

Do you want to add a sample characteristic?
ANSWER OPTIONS:
y:	yes
n:	no - same as STOP
0:	back
STOP:	cancel pipelinen

Is sc_seq:notes correct for description?
ANSWER OPTIONS:
y:	yes
Or type the correct attribute name:	  
0:	back
STOP:	cancel pipelineexperiment:notes

Is sc_seq:gene_expression correct for processed data file?
ANSWER OPTIONS:
y:	yes
Or type the correct attribute name:	  
0:	back
STOP:	cancel pipelinesc_seq:raw_counts_h5

Is sc_seq:raw_fastqs correct for raw?
ANSWER OPTIONS:
y:	yes
Or type the correct attribute name:	  
0:	back
STOP:	cancel pipeline
---------------------------------------------------------------------------
GeolineError                              Traceback (most recent call last)
<ipython-input-8-1d7d5f725620> in <module>
      1 assay = 'sc_seq' # accepted assays 'rna_seq', 'dna_seq', 'sc_seq'
      2 primary_model = 'sc_seq' # name of a model that has most of the data (e.g. rna_seq)
----> 3 geo_meta = gl.seq_workflow(assay, primary_model)

~/GitHub/monoetna/geoline/geoline/Geoline.py in seq_workflow(self, assay, primary_model, **kwargs)
     61         answer = self._magby_instance.query(self._project_name, query, **kwargs)
     62         if 'errors' in answer.keys():
---> 63             raise GeolineError(f'geoline._workflow(): Malformed magma query {answer["errors"]}')
     64         flat_answer = self._query_wrapper(answer['answer'], answer['format'])
     65         answer_df = self._organize_answer_df_columns(DataFrame(flat_answer), attribute_maps)

GeolineError: geoline._workflow(): Malformed magma query ['Expected an argument to Magma::RecordPredicate']
```

</details>

**Comment by Gvaihir** [comment]
> Trying again, now giving `raw_counts_h5` as the processed counts file, it looks like there is a malformed query somewhere. But I'm not sure where. Perhaps you could add a hint at the current data grab goal in the error messaging?
> 
> Click to expand choices and traceback
> ```
> Is sc_seq:tube_name correct for title?
> ANSWER OPTIONS:
> y:	yes
> Or type the correct attribute name:	  
> 0:	back
> STOP:	cancel pipeliney
> 
> Is sc_seq:biospecimen correct for source name?
> ANSWER OPTIONS:
> y:	yes
> Or type the correct attribute name:	  
> 0:	back
> STOP:	cancel pipelinesc_seq:biospecimen_group
> 
> Is subject:name correct for organism?
> ANSWER OPTIONS:
> y:	yes
> Or type the correct attribute name:	  
> 0:	back
> STOP:	cancel pipelinesubject:species
> 
> Do you want to add a sample characteristic?
> ANSWER OPTIONS:
> y:	yes
> n:	no - same as STOP
> 0:	back
> STOP:	cancel pipeliney
> 1:	tissue
> 2:	cell type
> 3:	treatment
> 4:	genotype
> 5:	disease state2
> Enter attribute name for this characteristicsc_seq:cell_fraction
> 
> Do you want to add a sample characteristic?
> ANSWER OPTIONS:
> y:	yes
> n:	no - same as STOP
> 0:	back
> STOP:	cancel pipelinen
> 
> Is sc_seq:notes correct for description?
> ANSWER OPTIONS:
> y:	yes
> Or type the correct attribute name:	  
> 0:	back
> STOP:	cancel pipelineexperiment:notes
> 
> Is sc_seq:gene_expression correct for processed data file?
> ANSWER OPTIONS:
> y:	yes
> Or type the correct attribute name:	  
> 0:	back
> STOP:	cancel pipelinesc_seq:raw_counts_h5
> 
> Is sc_seq:raw_fastqs correct for raw?
> ANSWER OPTIONS:
> y:	yes
> Or type the correct attribute name:	  
> 0:	back
> STOP:	cancel pipeline
> ---------------------------------------------------------------------------
> GeolineError                              Traceback (most recent call last)
> <ipython-input-8-1d7d5f725620> in <module>
>       1 assay = 'sc_seq' # accepted assays 'rna_seq', 'dna_seq', 'sc_seq'
>       2 primary_model = 'sc_seq' # name of a model that has most of the data (e.g. rna_seq)
> ----> 3 geo_meta = gl.seq_workflow(assay, primary_model)
> 
> ~/GitHub/monoetna/geoline/geoline/Geoline.py in seq_workflow(self, assay, primary_model, **kwargs)
>      61         answer = self._magby_instance.query(self._project_name, query, **kwargs)
>      62         if 'errors' in answer.keys():
> ---> 63             raise GeolineError(f'geoline._workflow(): Malformed magma query {answer["errors"]}')
>      64         flat_answer = self._query_wrapper(answer['answer'], answer['format'])
>      65         answer_df = self._organize_answer_df_columns(DataFrame(flat_answer), attribute_maps)
> 
> GeolineError: geoline._workflow(): Malformed magma query ['Expected an argument to Magma::RecordPredicate']
> ```

which project?

**Comment by Gvaihir** [comment]
> Trying again, now giving `raw_counts_h5` as the processed counts file, it looks like there is a malformed query somewhere. But I'm not sure where. Perhaps you could add a hint at the current data grab goal in the error messaging?
> 
> Click to expand choices and traceback

Is the attr type of `sc_seq:raw_counts_h5` - file or file collection?
If yes, it will throw an error cause I have not worked on queries for file attr types. Response is JSON, so query has to include a key or 'all'. Can you ignore files for the time being?

**Comment by dtm2451** [comment]
Hmm, sure-thing!  Will do.  I don't know those projects as well, but I do have access.

The only viable raw/processed sequencing data for "xcrs1" rn is the .h5 attribute I tried.  It is a file attribute, yes.  If I skip that, there are even more bugs, but presumably because then there's no seq-data anchoring which records to target!

**Comment by Gvaihir** [comment]
> Hmm, sure-thing! Will do. I don't know those projects as well, but I do have access.
> 
> The only viable raw/processed sequencing data for "xcrs1" rn is the .h5 attribute I tried. It is a file attribute, yes. If I skip that, there are even more bugs, but presumably because then there's no seq-data anchoring which records to target!

You do need to have at least one `model:attr` mapping to come from the primary model that you specify in `Geoline.seq_workflow()`

**Comment by Gvaihir** [comment]
> Just made a few attempts with IPI. Got errors for all three, and all different errors:
> 
> Initial setup:
> 
> ```
> # "Locally"
> git checkout gvaihir/geoline_debug
> git pull
> cd geoline
> jupyter notebook
> ```
> 
>  ```
> # In jupyter notebook
> pip install .
> 
> # Restarted the kernal, then...
> 
> from geoline import Geoline
> url = 'https://magma.ucsf.edu'
> token = '<<my_token>>'
> project = 'ipi' # name of a project you want to submit data from. It should exist in magma
> gl = Geoline.Geoline(url, token, project)
> assay = 'rna_seq' # accepted assays 'rna_seq', 'dna_seq', 'sc_seq'
> primary_model = 'rna_seq' # name of a model that has most of the data (e.g. rna_seq)
> 
> # Then I ran this three times, giving different inputs interactively
> geo_meta = gl.seq_workflow(assay, primary_model)
> ```
> 
> 1) title = string, raw = matrix, source name = parent-link <== **query malformed**
> 2) title = string, raw = matrix, source name = string from parent model <== **JSONDecodeError**
> 3) title = string, raw = matrix <== **'float' not subscriptable**

Cool, thanks for the report!
#1 - there's no way to know in advance what type of attribute is given. And I'm not sure how links can be resolved to any specific attribute. That's why the query is malformed. Links = no-no
#2 and #3 - I don't see the point of supporting matrices as an output for geo metadata. The only things you need form a file attribute is file name + md5. But again there's really no way to tell what attribute type is supplied by the user before a call to magma is done.
My solution is to add those details in the readme.

In the meantime I will test #2 or #3 but with the file attribute instead of matrix. If that works I will merge the pr.
Thanks!

**Comment by Gvaihir** [comment]
@dtm2451 
try this for 'mvir1' for 'rna_seq' as a primary model
```
'y', '', '',
'y', '3', 'treatment:name',   # characteristics
'y', '2', 'treatment:type', 'n',    # characteristics
'', 'rna_seq:genome_alignment', ''
```
I could not find any file mappings for sc_rna_seq model tho...

Feel free to play around with other mappings, but not 'links', 'matrices' or 'collections'. I will add those guidelines in the next pr
Thanks!

**Comment by dtm2451** [comment]
I should be able to do some testing with mvir1 tomorrow morning, and I'll let you know how it goes.

**Comment by dtm2451** [comment]
The given options for mvir1 worked for me.  I'll test with some adjustments after my currently scheduled meeting.

**Comment by dtm2451** [comment]
```
'y', 'patient:name', '',
'y', '1', 'rna_seq:compartment',   # characteristics
'y', '3', 'treatment:name',  # characteristics
'y', '5' 'patient:covid_status' # characteristics
'n'
'y' # rna_seq:notes works
'y' # rna_seq:gene_experssion works
'' # skip raw files
```
Worked, so can pull from the 

```
'y', 'patient:name', '',
'y', '1', 'rna_seq_plate:plate_name',   # characteristics
'y', '2', 'sc_rna_seq:biospecimen',  # characteristics
'n'
'y' # rna_seq:notes works
'y' # rna_seq:gene_experssion works
'' # skip raw files
```
worked as well!

**Comment by Gvaihir** [comment]
Perfect! Thanks so much! If you approve - I'd like to merge and close it

**Review by dtm2451 — APPROVED** [review]

**Pull request merged**
