### PR TITLE
metis client auto-refreshes token when it nears expiration

### PR DESCRIPTION
**Pull request by coleshaw**
This PR updates metis_client to check if a token is near expiration. If so, it calls Janus to get a new token so that long-lived downloads and uploads can occur without manual intervention.

### CODE REVIEW

**Comment by graft** [comment]
Looks neat! Does this obviate the need for a long lived token?

**Comment by coleshaw** [comment]
Hmmmm, I would say semi-obviates. The token in your environment still has to be a current token, so you can't have an open terminal that you keep re-using for a long time. But if you start the process with an active token, that singular process won't die in the middle. Starting a new process in that terminal would then require you to still fetch a new token from Janus (assuming the old one expired).

**Comment by graft** [comment]
Hmm, so this fixes interactive mode, but command mode (i.e. doing `metis_client <metis_path> <cmd>`) is still perhaps vulnerable to failure, since it would involve re-initializing the process and the token doesn't get re-exported.

**Comment by coleshaw** [comment]
Ah, great point! Let me poke around a little more.

**Comment by coleshaw** [comment]
So I'm not sure there's a way to re-export the refreshed token into the parent shell. Do you know if any of the users loop through individual commands using command mode? I think Arjun feeds in a file, i.e. `$ metis_client < instructions.txt`, which works with the current method because all the instructions are fed into a single instance of the client. Others use interactive mode.

**Comment by corps** [comment]
> So I'm not sure there's a way to re-export the refreshed token into the parent shell. Do you know if any of the users loop through individual commands using command mode? I think Arjun feeds in a file, i.e. `$ metis_client < instructions.txt`, which works with the current method because all the instructions are fed into a single instance of the client. Others use interactive mode.

So, exporting to the parent process's environment is explicitly impossible due to security without cooperation from the parent process.
What you can do, is have the child, for instance, output to stdout the new token, and the parent would have to watch the stdout and modify itself with the new token.  Otherwise, this isn't possible.

**Comment by corps** [comment]
You could have the command mode maybe write to a file the most "fresh" token on completion.

```
metis_client my_new_token.txt < my_commands # outputs TOKEN=ASDFASDFASDF to the my_new_token.txt file
source my_new_token.txt
```

**Comment by coleshaw** [comment]
So basically an informational message...? :+1:

**Comment by graft** [comment]
I don't think we should try to export out a new token. We could leave this be here, so that long-running single transactions are safe. Between metis_client commands, there is another machine-friendly route, which is to set a public key on your janus account and generate a new token as required in the shell. This might also be done automatically within metis_client, perhaps, if the user has a public key set on janus and a private key configured with metis_client.

**Comment by coleshaw** [comment]
Okay, that makes sense. If there's an alternate route for the command-method, I'll take out the export.

**Pull request merged**
