### PR TITLE
single-var bar_plots

### PR DESCRIPTION
**Pull request by dtm2451**
Updates the plotly bar_plotter to ... when x_by==y_by:
- Be able to run the summarization calcs 
- Skip assigning colors per category, and just use one (orange)
- Ignore the user's 'scale_by' request and always use 'counts' (because 'fraction' would always be 1, so doesn't make sense to use!)
image

### CODE REVIEW

**Comment by coleshaw** [comment]
I think this works, but small nit:

> Ignore the user's 'scale_by' request and always use 'counts' (because 'fraction' would always be 1, so doesn't make sense to use!)

Does this reflect in the UI, or is there a way to make it reflect in the UI, that this choice doesn't matter? i.e. by removing the box, removing the `fraction` option, etc.? Wondering if it'll be confusing if they accidentally pick `fraction` but nothing changes, or they wonder what the heck that means...

**Comment by dtm2451** [comment]
> I think this works, but small nit:
> 
> > Ignore the user's 'scale_by' request and always use 'counts' (because 'fraction' would always be 1, so doesn't make sense to use!)
> 
> Does this reflect in the UI, or is there a way to make it reflect in the UI, that this choice doesn't matter? i.e. by removing the box, removing the `fraction` option, etc.? Wondering if it'll be confusing if they accidentally pick `fraction` but nothing changes, or they wonder what the heck that means...

Thanks for the push!  Wasn't gonna do anything except maybe a note in the docs, but I can disable the input when x_by==y_by!

**Comment by dtm2451** [comment]
bar_plot-disable

**Comment by dtm2451** [comment]
Title also doesn't need the x_by info added.
... gonna sit with this for a day to make sure I don't notice another!

**Pull request merged**
