### PR TITLE
Swap to Material UI for Nav Bar

### PR DESCRIPTION
**Pull request by maflaven**
### Changes
- [x] use MUI components for nav bar (discussion here https://www.notion.so/ucsfdatascience/UI-tasks-f4629c9435df4a049490a5f79e0908ac)

image

### Discussion
- thoughts about having either app descriptions and/or names in App Menu?
- current app is excluded in App Menu. should we show it? including follows google's pattern
- drop shadow for nav bar or leave as is?
- ignore responsiveness for now?

### CODE REVIEW

**Comment by dtm2451** [comment]
My own thoughts on the discussion points:
> - thoughts about having either app descriptions and/or names in App Menu?

For cleanliness / space, I like having the descriptions only as the text.  Seems fine to me to have the app names only show on hover, and that should be something we can do with MUI if you don't already have it that way!

> - current app is excluded in App Menu. should we show it? including follows google's pattern

I think let's show it!

> - drop shadow for nav bar or leave as is?

I can go either way on this, but if we do keep the drop shaddow, I think it needs to be on the left side as well and the bottom (looks to be only on the bottom currently)

> - ignore responsiveness for now?

How unresponsive does it feel???  I don't think we want to release something that might feel like a downgrade, but I'll test when I get a chance to give a better answer!

**Comment by graft** [comment]
+1 to include current app, I often find the variable layout of the nav confusing, it would also make an even number of apps, so could be a 2x3 grid.

Re: names etc., I think names in the tooltip/title and descriptions as subtext is best; both are necessary but showing descriptions is more friendly to novices. I might limit descriptions to a single word, like Timur - Browse, Metis - Store, Janus - Auth, Polyphemus -  Link, Vulcan - Analyze, Gnomon - Name. "Store" and "Auth" seem kind of weak but I can't think of a better pithy verb here.

A few nits:
- I would get rid of "Apps" to save screen realestate in the nav
- maybe see if the popup can emerge from below the icon rather than below the nav

**Comment by dtm2451** [comment]
Maybe "Files" for the Metis descriptor instead of "Store"?

**Comment by maflaven** [comment]
> * I would get rid of "Apps" to save screen realestate in the nav

done 
> * maybe see if the popup can emerge from below the icon rather than below the nav

done

- switched to single word verb for now
- re: drop shadow, I meant for the nav bar itself. MUI default has one but I can go either way

**Comment by maflaven** [comment]
> How unresponsive does it feel??? I don't think we want to release something that might feel like a downgrade, but I'll test when I get a chance to give a better answer!

I mean in the dynamic window size sense. it's actually pretty snappy!

**Comment by graft** [comment]
> * re: drop shadow, I meant for the nav bar itself. MUI default has one but I can go either way

Oh yes - I would flatten this out for sure, the nav bar should integrate well with the rest of the page.

A few alignment tweaks:
- The height of the navbar should stay exactly 61px. There are a number of pages that use calc() to subtract this amount, which may cause strange issues if they deviate by a small amount (like stray scrollbars-within-scrollbars suddenly appearing)
- It looks like there is now some extra padding on left and right of the nav bar, might want to slim this back down

**Comment by maflaven** [comment]
@graft @dtm2451 all the tweaks/discussion points have been address.

**Comment by dtm2451** [comment]
The spacing at the top still seems different?

Production:
image

Here:
image

**Comment by dtm2451** [comment]
Also I think "Browse" > "Model" for timur.  @graft?

**Comment by maflaven** [comment]
> The spacing at the top still seems different?

Should match exactly now save for slightly more spacing next to the app menu button to account for it's size.

**Comment by amadeovezz** [comment]
@maflaven I've just merged in the Makefile changes we were working on

**Comment by amadeovezz** [comment]
this is looking great!

**Pull request merged**
