### PR TITLE
use update_json when creating Magma project record

### PR DESCRIPTION
**Pull request by coleshaw**
This PR updates the `etna` gem to `0.1.45`. It changes the method called when creating a Magma project record in the `create_project_workflow`, which seems to address the issues seen in #919.

To test it, you'll need to build the `etna` gem locally and install it.

```
$ make -C etna bash
-> gem build etna
-> exit
$ cd etna/
$ gem uninstall etna (type y to confirm, when prompted)
$ gem install etna
$ gem list | grep etna (should show etna  0.1.45)
$ etna administrate project create <test_project> "Test project" --environment development
```

For me this works on 2.7.6 now, even if I run it multiple times against the same arguments:

```
$ ruby --version
ruby 2.7.6p219 (2022-04-12 revision c9c2245c0a) [x86_64-linux]
$ etna administrate project create test_proj6 "Test Project6" --environment development
Creating Janus project.
Done! Adding you as an administrator on the project.
Done with setting up the project in Janus!
Creating the project in Magma.
Done! Adding your new project record.
Add more users? Y/n
n
All complete!
You need to visit Janus to refresh your token.
You can now log into any app to manage your data.
$ etna administrate project create test_proj6 "Test Project6" --environment development
Creating Janus project.
Done! Adding you as an administrator on the project.
Done with setting up the project in Janus!
Creating the project in Magma.
Done! Adding your new project record.
Add more users? Y/n
n
All complete!
You need to visit Janus to refresh your token.
You can now log into any app to manage your data.
$ gem list | grep etna
etna (0.1.45)
```

The `magma_client.update` method parses everything into a multipart/form-data structure, which causes the nested `revisions` hash to flatten into a set of array-inputs. It looks like the `multipart-post` library [changed six months ago](https://github.com/socketry/multipart-post/blame/e52ef1e11b1f1edfc3ae16eff24a71a53745c967/lib/multipart/post/multipartable.rb) to use the `transform_keys` method, which assumes a hash is passed in. Previously it used `map` on the params, which would have worked for our Array-ish inputs, I think.

`magma_client.update_json` sends the request as just a JSON structure, which is all we need in this case. We only require `magma_client.update` when sending large updates, I think...

### CODE REVIEW

**Comment by coleshaw** [comment]
And I think the reason it worked for me on 2.5.7 is because I have an older version of `multipart-post` installed:

```
$ gem list | grep multipart
multipart-post (2.1.1)
```

If you freshly installed things in your local 2.5.7, you would have gotten the latest `multipart-post` (2.2.3), which would have just led to the same bug / issue.

**Comment by coleshaw** [comment]
I've pinned the dependency to the last version of `multipart-post` that works with our current code. Scanning the code, I'm not sure that the latest versions would be compatible with our version in `multipart_serializable_nested_hash.rb`, which I think we would want to verify is a solid replacement before using newer versions.

**Comment by corps** [comment]
Excellent catch!

**Review by corps — APPROVED** [review]

**Review by dtm2451 — APPROVED** [review]
Works from my system that had had a too-recent multipart-post beforehand.
```
dan@pop-os:~/GitHub/monoetna$ gem list | grep etna
etna (0.1.45)
dan@pop-os:~/GitHub/monoetna$ etna administrate project create test_project "Test project" --environment development
Creating Janus project.
Done! Adding you as an administrator on the project.
Done with setting up the project in Janus!
Creating the project in Magma.
Done! Adding your new project record.
Add more users? Y/n
n
All complete!
You need to visit Janus to refresh your token.
You can now log into any app to manage your data.
dan@pop-os:~/GitHub/monoetna$
```

**Pull request merged**
