### PR TITLE
suppress templates if asked

### PR DESCRIPTION
**Pull request by graft**
Cf. Zach's remark in slack, the ability to not return a template if you so desire.

### CODE REVIEW

**Review by coleshaw — APPROVED** [review]

**Review by dtm2451 — APPROVED** [review]

**Comment by dtm2451** [comment]
Just double checking my understanding... I'll test it out & add explicitly into magmaR later.

It works via a new `hide_templates` input which defaults to `nil`? What happens if it is given explicitly as `false`?

**Comment by graft** [comment]
> It works via a new `hide_templates` input which defaults to `nil`? What happens if it is given explicitly as `false`?

`@hide_templates = !!@params[:hide_templates]` converts the input to `true` or `false`, so it should be equivalent to leaving it out.

**Comment by dtm2451** [comment]
I'll ping again once I have a chance to test!

**Comment by dtm2451** [comment]
Just kidding lol... I can't test in production/staging until it's deployed, and I can't actually use magmaR with my dev setup until after I complete part of my magmaR PR.  Deploy whenever as far as I'm concerned!

**Pull request merged**
